import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <head>
        <Script src="https://kit.fontawesome.com/2a40c3d92f.js" crossOrigin="anonymous"/>
      </head>
      <body className="bg-black ">{children}</body>
    </html>
  );
}
