import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <head>
        <script src="https://kit.fontawesome.com/2a40c3d92f.js" crossorigin="anonymous"></script>
      </head>
      <body className="bg-black ">{children}</body>
    </html>
  );
}
